import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME!,
  description: "Generated by create next app",
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'min-h-dvh'}>
        {children}
      </body>
    </html>
  )
}
